config/routes.rb
RailsWeb::Application.routes.draw do

  root :to => "home#index"

  resources :gamers

end

app/models/game.rb
class Game < ActiveRecord::Base

  attr_accessible :name

  validates_presence_of :name

  has_many :gamers, :through => :scores
  has_many :scores, :dependent => :destroy

end

app/models/gamer.rb
class Gamer < ActiveRecord::Base

  attr_accessible :tag, :firstname, :lastname, :password

  validates_presence_of :tag, :firstname, :lastname, :password
  validates :tag, :format => {
    :with => /^[\w\-][0-9\w\-]*$/,
    :message => "Gamer tag must start with a letter and can only contain letters, numbers, and symbols { `_`, `-` }"
  }
  validates :firstname, :format => {
    :with => /^[A-Za-z'\-]$/,
    :message => "Bad format for first name"
  }
  validates :lastname, :format => {
    :with => /^[A-Za-z'\-]$/,
    :message => "Bad format for last name"
  }

  has_many :games, :through => :scores
  has_many :scores, :dependent => :destroy

  def self.login?( user, pass )
    Gamer.first( :conditions => { :tag => user, :password => pass } )
  end

end

app/models/score.rb
class Score < ActiveRecord::Base

  attr_accessible :gamer_id, :game_id, :points

  validates_presence_of :gamer_id, :game_id, :points

  belongs_to :gamer
  belongs_to :game

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gamers_controller.rb
class GamersController < ApplicationController

  before_filter :get_gamers, :only => [ "index" ]

  def get_gamers
    @gamers = Gamer.all( :order => "tag" )
  end

  def index
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gamers/index.html.haml
%h1 Players in the community

%p= "#{ @gamers.length } users have signed up!"

%p
  = form_tag( gamers_path, :method => :post ) do
    Join now!
    %table.form
      %tr
        %th Username:
        %td= text_field_tag( "tag", nil, :maxlength => 50 )
      %tr
        %th First Name:
        %td= text_field_tag( "firstname", nil, :maxlength => 255 )
      %tr
        %th Last Name:
        %td= text_field_tag( "lastname", nil, :maxlength => 255 )
      %tr
        %td.align_right= check_box_tag( "show_last_name", "1", true )
        %td Show last name in profile
      %tr
        %th Password:
        %td= password_field_tag( "password", nil, :maxlength => 255 )
      %tr
        %th Confirm Password:
        %td= password_field_tag( "cpassword", nil, :maxlength => 255 )
      %tr
        %td= submit_tag( "Create account" )

%p
  %table.big
    %tr
      %th User Tag
    - @gamers.each do | gamer |
      %tr
        %td= gamer.tag

app/views/home/index.html.haml
%h1 Welcome

%p
  Temporary links
  %br
  = link_to( "Gamers", gamers_path )

app/views/layouts/application.html.haml
<!DOCTYPE html>
!!!
%html
  %head
    %title= "Some Title"
    = stylesheet_link_tag( "application", :media => "all" )
    = csrf_meta_tags
  %body
    #content
      = yield
    = javascript_include_tag( "application" )